### ISSUE TITLE
How to adjust verbosity?

### ISSUE THREAD

**Issue by zoffixznet** [perl6/tap-harness6#14]
@Leont would you know how to adjust verbosity of the output?

I see there's this enum, which suggests it's possible, but I'm having trouble finding the user-facing knob to turn to achive these volumes:

```perl6
enum Formatter::Volume <Silent ReallyQuiet Quiet Normal Verbose>;
```

[Trying to make output](https://github.com/travis-ci/docs-travis-ci-com/pull/1190#issuecomment-303762219) `Verbose`, like `prove -v` so all the test details get printed.

**Comment by Leont** [comment]
I refactored the formatter extensively because various things (including this) were broken. It should be reimplemented. Doing it correctly is a bit tricky, since it rather interferes with the interactive output, it may actually need a reporter of its own.

**Comment by Leont** [comment]
See #15 :-)
