### ISSUE TITLE
prove6 cant handle multiple -I

### ISSUE THREAD

**Issue by ufobat** [perl6/tap-harness6#18]
I would be happy if prove6 could actually handle multiple -I to include several libs. I think perl5 prove is able to do so.

**Comment by Leont** [comment]
Not sure I can really do better with the built-in command-line parsing, though given TAP.pm is out of core now I may be able to use [Getopt::Long](https://github.com/Leont/getopt-long6) :-)

**Comment by ufobat** [comment]
or is there maybe a different way to include more then one libariy path?

**Comment by ugexe** [comment]
One way to handle it is by removing the type constraint:
```
$ perl6 -e 'sub MAIN(:I(:$incdir)) { say $incdir.join(",") }' --I=1 --I=2
1,2

$ perl6 -e 'sub MAIN(:I(:$incdir)) { say $incdir.join(",") }' --I=1
1
```

**Comment by Leont** [comment]
> One way to handle it is by removing the type constraint:

That is rather unexpected!… (and I don't remember this being documented)

**Comment by ugexe** [comment]
I'm not sure if it is specifically documented for MAIN parameters, but the behavior can be seen outside of that context:
```
$ perl6 -e 'my $x := 1; say $x'
1

$ perl6 -e 'my $x := 1,2; say $x'
(1 2)
```

**Comment by Leont** [comment]
Pushed a fix :-)
