### ISSUE TITLE
All tests successful but Result: FAILED

### ISSUE THREAD

**Issue by ufobat** [perl6/tap-harness6#21]
Hey :-)
We noticed that prove6 reports a failure even though all tests did pass:

https://github.com/Bailador/Bailador/issues/284
https://travis-ci.org/Bailador/Bailador/builds/314951529

Thank you very much.

**Comment by Leont** [comment]
And probably a `--loose` fixes that. That is already default on older rakudos in `TAP::Harness` (old `Test.pm` generates invalid TAP for subtests), but `prove6` accidentally overrides that.

**Comment by Leont** [comment]
Fixed, sorry I forgot about that.
