### ISSUE TITLE
prove6 -v exception thrown on "Bash on Ubuntu on Windows"

### ISSUE THREAD

**Issue by hankache** [perl6/tap-harness6#22]
Running `prove6 -v` on "Bash on Ubuntu on Windows" throws the following exception:
```
Unhandled exception in code scheduled on thread 6
Cannot flush handle: Failed to flush filehandle: Input/output error
  in block  at /home/kmel/.perl6/sources/850D4CD3715B1F98EE30D84A228A851CCD444986 (TAP) line 914

**Comment by Leont** [comment]
Weird. I could ignore flush failures I guess, but I'd like to understand what's going on first.

**Comment by zoffixznet** [comment]
@hankache what's your perl6 version?

**Comment by zoffixznet** [comment]
I believe this should be fixed by a commit that just went in to rakudo:

Fix:  https://github.com/MoarVM/MoarVM/commit/4541cf6f6c
      https://github.com/perl6/nqp/commit/659ced5b57
      https://github.com/rakudo/rakudo/commit/096c4eadbe
Test: https://github.com/perl6/roast/commit/dcce881633

**Comment by hankache** [comment]
Working on:
This is Rakudo version 2017.12-64-g096c4ea built on MoarVM version 2017.12-14-g4541cf6                                  implementing Perl 6.c.

@zoffixznet++

**Comment by Leont** [comment]
@zoffixznet++ indeed
